### ISSUE TITLE
Home Assistant - Entity "service_needed"

### ISSUE THREAD

**Issue by Daikon2022** [kotope/valloxesp#23]
Are there any plans to publish the "service_needed" informationen in HA? The information is already available in the MQTT informations.

**Comment by kotope** [comment]
At least my device informed service_needed flag static and did not change even though maintenance counter did drop to zero.
Since I don't know what the service_needed flag actually is (or if it's even working) I've decided not to include in HA end yet.

Unless of course someone (you?) knows what it actually is :-)

**Comment by kotope** [comment]
Good to know! Seems like it's then quite much dependant of the ventilation machine. I will add this feature in the next release.

**Comment by kotope** [comment]
This is implemented and released now (finally) :)
